const GROUP_API="https://energy-school-api.energypublishing.workers.dev",groupToken=sessionStorage.getItem("energySchoolToken")||localStorage.getItem("energySchoolToken");
let groupData={groups:[],subjects:[],teachers:[]},rosterData={students:[],available:[]},activeGroupId=0;
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function groupApi(path,options={}){const r=await fetch(GROUP_API+path,{...options,headers:{Authorization:`Bearer ${groupToken}`,"Content-Type":"application/json",...(options.headers||{})}}),d=await r.json();if(!r.ok)throw new Error(d.error||"Грешка при заявката.");return d}
async function loadGroups(){groupMessage.textContent="Зареждане...";try{groupData=await groupApi("/api/admin/groups");groupSubject.innerHTML=groupData.subjects.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join("");groupTeacher.innerHTML=groupData.teachers.map(t=>`<option value="${t.id}">${esc(t.first_name)} ${esc(t.last_name)}</option>`).join("");groupMessage.textContent="";renderGroups()}catch(e){groupMessage.textContent=e.message}}
function renderGroups(){const q=groupSearch.value.trim().toLowerCase(),status=groupStatus.value,rows=groupData.groups.filter(g=>(`${g.name} ${g.subject_name} ${g.teacher_name}`).toLowerCase().includes(q)&&(status==="all"||g.status===status));groupsGrid.innerHTML=rows.map(g=>`<article class="group-card" style="--group-color:${esc(g.color||"#f97316")}"><h2>${esc(g.name)}</h2><p>${esc(g.subject_name)}</p><dl><div><dt>Учител</dt><dd>${esc(g.teacher_name)}</dd></div><div><dt>Ученици</dt><dd>${Number(g.student_count)}</dd></div><div><dt>Кабинет</dt><dd>${esc(g.room||"—")}</dd></div><div><dt>Статус</dt><dd>${g.status==="active"?"Активна":"Архивирана"}</dd></div></dl><div class="group-actions"><button data-roster="${g.id}">Ученици</button><button data-edit="${g.id}">Редактирай</button></div></article>`).join("")||'<div class="empty-state"><b>Няма намерени учебни групи.</b></div>';const active=groupData.groups.filter(g=>g.status==="active");groupCount.textContent=active.length;groupStudentCount.textContent=active.reduce((n,g)=>n+Number(g.student_count),0);groupTeacherCount.textContent=new Set(active.map(g=>g.teacher_id)).size;groupSubjectCount.textContent=new Set(active.map(g=>g.subject_id)).size}
function openGroup(g=null){groupForm.reset();groupId.value=g?.id||"";groupName.value=g?.name||"";groupSubject.value=g?.subject_id||groupData.subjects[0]?.id||"";groupTeacher.value=g?.teacher_id||groupData.teachers[0]?.id||"";groupRoom.value=g?.room||"";groupEditStatus.value=g?.status||"active";document.querySelectorAll("#groupForm .edit-only").forEach(x=>x.hidden=!g);groupModalTitle.textContent=g?"Редактиране на група":"Нова учебна група";groupError.textContent="";groupModal.hidden=false}
document.querySelectorAll(".group-dismiss").forEach(b=>b.onclick=()=>groupModal.hidden=true);addGroup.onclick=()=>openGroup();groupSearch.oninput=renderGroups;groupGlobalSearch.oninput=()=>{groupSearch.value=groupGlobalSearch.value;renderGroups()};groupStatus.onchange=renderGroups;
groupForm.onsubmit=async e=>{e.preventDefault();groupError.textContent="Запазване...";const id=groupId.value,payload={name:groupName.value,subjectId:Number(groupSubject.value),teacherId:Number(groupTeacher.value),room:groupRoom.value,status:groupEditStatus.value};try{await groupApi(id?`/api/admin/groups/${id}`:"/api/admin/groups",{method:id?"PATCH":"POST",body:JSON.stringify(payload)});groupModal.hidden=true;await loadGroups()}catch(x){groupError.textContent=x.message}};
groupsGrid.onclick=e=>{const roster=e.target.dataset.roster,edit=e.target.dataset.edit;if(edit)openGroup(groupData.groups.find(g=>Number(g.id)===Number(edit)));if(roster)openRoster(Number(roster))};
async function openRoster(id){activeGroupId=id;rosterMessage.textContent="Зареждане...";rosterModal.hidden=false;try{rosterData=await groupApi(`/api/admin/groups/${id}/students`);rosterTitle.textContent=rosterData.group.name;rosterMeta.textContent=`${rosterData.group.subject_name} · ${rosterData.group.teacher_name}`;rosterMessage.textContent="";renderRoster()}catch(e){rosterMessage.textContent=e.message}}
function renderRoster(){const q=rosterSearch.value.trim().toLowerCase();availableStudent.innerHTML='<option value="">Избери ученик за добавяне</option>'+rosterData.available.map(s=>`<option value="${s.id}">${esc(s.first_name)} ${esc(s.last_name)} · ${esc(s.class_name||"без клас")}</option>`).join("");groupStudents.innerHTML=rosterData.students.filter(s=>(`${s.first_name} ${s.last_name} ${s.class_name||""}`).toLowerCase().includes(q)).map(s=>`<div class="group-student"><i>${esc(s.first_name[0]+s.last_name[0])}</i><span><b>${esc(s.first_name)} ${esc(s.last_name)}</b><small>${esc(s.class_name||"Без официална паралелка")} · ${esc(s.email)}</small></span><button data-remove-student="${s.id}">Премахни</button></div>`).join("")||'<div class="dashboard-empty">В групата няма ученици.</div>'}
document.querySelectorAll(".roster-dismiss").forEach(b=>b.onclick=()=>rosterModal.hidden=true);rosterSearch.oninput=renderRoster;addStudentToGroup.onclick=async()=>{if(!availableStudent.value)return;try{await groupApi(`/api/admin/groups/${activeGroupId}/students`,{method:"POST",body:JSON.stringify({studentId:Number(availableStudent.value)})});await openRoster(activeGroupId);await loadGroups()}catch(e){rosterMessage.textContent=e.message}};groupStudents.onclick=async e=>{const id=e.target.dataset.removeStudent;if(!id)return;try{await groupApi(`/api/admin/groups/${activeGroupId}/students/${id}`,{method:"DELETE"});await openRoster(activeGroupId);await loadGroups()}catch(x){rosterMessage.textContent=x.message}};
loadGroups();
