const toggle=document.querySelector("#showPassword"),password=document.querySelector("#password");if(toggle&&password)toggle.addEventListener("click",()=>{password.type=password.type==="password"?"text":"password";toggle.textContent=password.type==="password"?"Покажи":"Скрий"});const loginForm=document.querySelector("#loginForm");if(loginForm)loginForm.addEventListener("submit",e=>{e.preventDefault();document.querySelector("#message").textContent="Реалният вход ще бъде активиран при Cloudflare интеграцията."});const menu=document.querySelector(".hamburger");if(menu)menu.addEventListener("click",()=>document.querySelector("aside").classList.toggle("open"));

const usersBody=document.querySelector("#usersBody");
if(usersBody){
 const seed=[{id:1,first:"Кристиян",last:"Марков",email:"student@energy-school.bg",role:"student",group:"11а клас",status:"active"},{id:2,first:"Анна",last:"Петрова",email:"teacher@energy-school.bg",role:"teacher",group:"Учител по английски",status:"active"},{id:3,first:"Иван",last:"Димитров",email:"director@energy-school.bg",role:"admin",group:"Директор",status:"active"},{id:4,first:"Мария",last:"Иванова",email:"m.ivanova@school.bg",role:"teacher",group:"Учител по математика",status:"active"},{id:5,first:"Никол",last:"Георгиева",email:"n.georgieva@school.bg",role:"student",group:"10б клас",status:"inactive"}];
 let users=JSON.parse(localStorage.getItem("energySchoolUsers")||"null")||seed;
 const modal=document.querySelector("#userModal"),form=document.querySelector("#userForm"),search=document.querySelector("#userSearch"),globalSearch=document.querySelector("#globalSearch"),roleFilter=document.querySelector("#roleFilter"),statusFilter=document.querySelector("#statusFilter");
 const labels={student:"Ученик",teacher:"Учител",admin:"Директор"};
 function save(){localStorage.setItem("energySchoolUsers",JSON.stringify(users))}
 function render(){const q=(search.value||"").toLowerCase();const filtered=users.filter(u=>(u.first+" "+u.last+" "+u.email+" "+u.group).toLowerCase().includes(q)&&(roleFilter.value==="all"||u.role===roleFilter.value)&&(statusFilter.value==="all"||u.status===statusFilter.value));usersBody.innerHTML=filtered.map(u=>`<tr><td><div class="person"><i>${u.first[0]}${u.last[0]}</i><span><b>${u.first} ${u.last}</b><small>${u.email}</small></span></div></td><td><span class="role role-${u.role}">${labels[u.role]}</span></td><td>${u.group}</td><td><span class="status ${u.status}">${u.status==="active"?"Активен":"Неактивен"}</span></td><td><button class="row-action" data-edit="${u.id}">Редактирай</button></td></tr>`).join("");document.querySelector("#emptyUsers").hidden=filtered.length>0;document.querySelector("#allCount").textContent=users.length;document.querySelector("#studentCount").textContent=users.filter(u=>u.role==="student").length;document.querySelector("#teacherCount").textContent=users.filter(u=>u.role==="teacher").length;document.querySelector("#activeCount").textContent=users.filter(u=>u.status==="active").length}
 function open(user){modal.hidden=false;document.body.classList.add("modal-open");document.querySelector("#modalTitle").textContent=user?"Редактиране на потребител":"Добавяне на потребител";document.querySelector("#editId").value=user?.id||"";document.querySelector("#firstName").value=user?.first||"";document.querySelector("#lastName").value=user?.last||"";document.querySelector("#userEmail").value=user?.email||"";document.querySelector("#userRole").value=user?.role||new URLSearchParams(location.search).get("add")||"student";document.querySelector("#userGroup").value=user?.group||""}
 function close(){modal.hidden=true;document.body.classList.remove("modal-open");form.reset();document.querySelector("#temporaryPassword").value="Energy2026!"}
 document.querySelector("#addUserButton").onclick=()=>open();document.querySelector("#closeModal").onclick=close;document.querySelector("#cancelModal").onclick=close;modal.addEventListener("click",e=>{if(e.target===modal)close()});[search,roleFilter,statusFilter].forEach(el=>el.addEventListener("input",render));globalSearch.addEventListener("input",()=>{search.value=globalSearch.value;render()});usersBody.addEventListener("click",e=>{const id=e.target.dataset.edit;if(id)open(users.find(u=>u.id===Number(id)))});
 form.addEventListener("submit",e=>{e.preventDefault();const id=Number(document.querySelector("#editId").value);const record={id:id||Date.now(),first:document.querySelector("#firstName").value.trim(),last:document.querySelector("#lastName").value.trim(),email:document.querySelector("#userEmail").value.trim(),role:document.querySelector("#userRole").value,group:document.querySelector("#userGroup").value.trim(),status:"active"};if(id)users=users.map(u=>u.id===id?{...u,...record}:u);else users.unshift(record);save();close();render()});render();if(new URLSearchParams(location.search).has("add"))open();
}

document.querySelectorAll(".app nav a").forEach(link=>{if(link.textContent.includes("Учебна година"))link.href="admin-year.html"});
const yearTabs=document.querySelectorAll("[data-year-tab]");
if(yearTabs.length){
 yearTabs.forEach(tab=>tab.addEventListener("click",()=>{yearTabs.forEach(x=>x.classList.toggle("active",x===tab));document.querySelectorAll("[data-year-panel]").forEach(panel=>panel.classList.toggle("active",panel.dataset.yearPanel===tab.dataset.yearTab))}));
 const holidaySeed=[{id:1,name:"Есенна ваканция",start:"2026-10-31",end:"2026-11-02"},{id:2,name:"Коледна ваканция",start:"2026-12-24",end:"2027-01-04"},{id:3,name:"Междусрочна ваканция",start:"2027-02-01",end:"2027-02-02"},{id:4,name:"Пролетна ваканция",start:"2027-04-03",end:"2027-04-11"}];let holidays=JSON.parse(localStorage.getItem("energySchoolHolidays")||"null")||holidaySeed;
 const subjectSeed=[{id:1,name:"Български език и литература",short:"БЕЛ",color:"#ef4444",status:"active"},{id:2,name:"Математика",short:"МАТ",color:"#3b82f6",status:"active"},{id:3,name:"Английски език",short:"АЕ",color:"#8b5cf6",status:"active"},{id:4,name:"Информационни технологии",short:"ИТ",color:"#f97316",status:"active"},{id:5,name:"История и цивилизации",short:"ИСТ",color:"#d97706",status:"active"},{id:6,name:"Физическо възпитание и спорт",short:"ФВС",color:"#10b981",status:"active"}];let subjects=JSON.parse(localStorage.getItem("energySchoolSubjects")||"null")||subjectSeed;
 const holidayModal=document.querySelector("#holidayModal"),subjectModal=document.querySelector("#subjectModal"),holidayList=document.querySelector("#holidaysList"),subjectsGrid=document.querySelector("#subjectsGrid"),subjectSearch=document.querySelector("#subjectSearch"),subjectStatus=document.querySelector("#subjectStatus");
 const bg={bg:"#fff7ed"};
 function dateBg(value){return new Intl.DateTimeFormat("bg-BG",{day:"numeric",month:"short",year:"numeric"}).format(new Date(value+"T12:00:00"))}
 function renderHolidays(){holidays.sort((a,b)=>a.start.localeCompare(b.start));holidayList.innerHTML=holidays.map(h=>`<article class="card holiday-row"><span class="holiday-icon">□</span><div><h3>${h.name}</h3><p>${dateBg(h.start)} – ${dateBg(h.end)}</p></div><span class="holiday-days">${Math.round((new Date(h.end)-new Date(h.start))/86400000)+1} дни</span><button data-delete-holiday="${h.id}">Премахни</button></article>`).join("")}
 function renderSubjects(){const q=subjectSearch.value.toLowerCase(),status=subjectStatus.value;subjectsGrid.innerHTML=subjects.filter(s=>s.name.toLowerCase().includes(q)&&(status==="all"||s.status===status)).map(s=>`<article class="subject-row"><i style="background:${s.color}"></i><div><b>${s.name}</b><small>${s.short}</small></div><span class="status ${s.status}">${s.status==="active"?"Активен":"Неактивен"}</span><button data-toggle-subject="${s.id}">${s.status==="active"?"Деактивирай":"Активирай"}</button></article>`).join("")}
 function openModal(modal){modal.hidden=false;document.body.classList.add("modal-open")}function closeModal(modal){modal.hidden=true;document.body.classList.remove("modal-open")}
 document.querySelector("#addHoliday").onclick=()=>openModal(holidayModal);document.querySelectorAll(".modal-dismiss").forEach(b=>b.onclick=()=>closeModal(holidayModal));document.querySelector("#addSubject").onclick=()=>openModal(subjectModal);document.querySelectorAll(".subject-dismiss").forEach(b=>b.onclick=()=>closeModal(subjectModal));
 document.querySelector("#holidayForm").addEventListener("submit",e=>{e.preventDefault();const start=document.querySelector("#holidayStart").value,end=document.querySelector("#holidayEnd").value;if(end<start){alert("Крайната дата не може да бъде преди началната.");return}holidays.push({id:Date.now(),name:document.querySelector("#holidayName").value.trim(),start,end});localStorage.setItem("energySchoolHolidays",JSON.stringify(holidays));e.target.reset();closeModal(holidayModal);renderHolidays()});holidayList.addEventListener("click",e=>{const id=e.target.dataset.deleteHoliday;if(id&&confirm("Да премахнем ли този период?")){holidays=holidays.filter(h=>h.id!==Number(id));localStorage.setItem("energySchoolHolidays",JSON.stringify(holidays));renderHolidays()}});
 document.querySelector("#subjectForm").addEventListener("submit",e=>{e.preventDefault();subjects.push({id:Date.now(),name:document.querySelector("#subjectName").value.trim(),short:document.querySelector("#subjectShort").value.trim().toUpperCase(),color:document.querySelector("#subjectColor").value,status:"active"});localStorage.setItem("energySchoolSubjects",JSON.stringify(subjects));e.target.reset();document.querySelector("#subjectColor").value="#f97316";closeModal(subjectModal);renderSubjects()});subjectsGrid.addEventListener("click",e=>{const id=e.target.dataset.toggleSubject;if(id){subjects=subjects.map(s=>s.id===Number(id)?{...s,status:s.status==="active"?"inactive":"active"}:s);localStorage.setItem("energySchoolSubjects",JSON.stringify(subjects));renderSubjects()}});[subjectSearch,subjectStatus].forEach(el=>el.addEventListener("input",renderSubjects));renderHolidays();renderSubjects();
}

document.addEventListener("click",e=>{const id=e.target?.dataset?.view;if(id){e.stopPropagation();location.href="admin-class-students.html?id="+id}},true);
const rosterBody=document.querySelector("#rosterBody");
if(rosterBody){
 const classId=Number(new URLSearchParams(location.search).get("id"))||1;
 const classes=JSON.parse(localStorage.getItem("energySchoolClasses")||"null")||[{id:1,grade:"8",letter:"а",teacher:"Мария Иванова",students:24,room:"204",profile:"Чужди езици",status:"active"}];
 const currentClass=classes.find(c=>c.id===classId)||classes[0];
 const allSeed=[{id:101,first:"Александър",last:"Петров",email:"a.petrov@school.bg",gender:"male"},{id:102,first:"Виктория",last:"Иванова",email:"v.ivanova@school.bg",gender:"female"},{id:103,first:"Мартин",last:"Георгиев",email:"m.georgiev@school.bg",gender:"male"},{id:104,first:"Елена",last:"Димитрова",email:"e.dimitrova@school.bg",gender:"female"},{id:105,first:"Николай",last:"Стоянов",email:"n.stoyanov@school.bg",gender:"male"},{id:106,first:"София",last:"Николова",email:"s.nikolova@school.bg",gender:"female"},{id:107,first:"Калоян",last:"Тодоров",email:"k.todorov@school.bg",gender:"male"},{id:108,first:"Дарина",last:"Попова",email:"d.popova@school.bg",gender:"female"},{id:109,first:"Борис",last:"Колев",email:"b.kolev@school.bg",gender:"male"},{id:110,first:"Йоана",last:"Ангелова",email:"y.angelova@school.bg",gender:"female"}];
 const created=(JSON.parse(localStorage.getItem("energySchoolUsers")||"[]")).filter(u=>u.role==="student").map(u=>({id:u.id,first:u.first,last:u.last,email:u.email,gender:u.gender||"male"}));const allStudents=[...allSeed,...created.filter(x=>!allSeed.some(s=>s.email===x.email))];const storageKey="energySchoolRoster:"+currentClass.id;let roster=JSON.parse(localStorage.getItem(storageKey)||"null")||allSeed.slice(0,8);
 const search=document.querySelector("#rosterSearch"),globalSearch=document.querySelector("#rosterGlobalSearch"),gender=document.querySelector("#genderFilter"),modal=document.querySelector("#studentPickerModal"),pickerSearch=document.querySelector("#pickerSearch"),pickerList=document.querySelector("#studentPickerList");
 document.querySelector("#rosterClassName").textContent=currentClass.grade+currentClass.letter;document.querySelector("#rosterTitle").textContent=currentClass.grade+currentClass.letter+" клас";document.querySelector("#rosterMeta").textContent=(currentClass.profile||"Общообразователна подготовка")+" · Класен ръководител: "+currentClass.teacher+" · Стая "+currentClass.room;
 function saveRoster(){localStorage.setItem(storageKey,JSON.stringify(roster))}
 function renderRoster(){const q=search.value.toLowerCase();const filtered=roster.filter(s=>(s.first+" "+s.last+" "+s.email).toLowerCase().includes(q)&&(gender.value==="all"||s.gender===gender.value));rosterBody.innerHTML=filtered.map((s,i)=>`<tr><td>${i+1}</td><td><div class="person"><i>${s.first[0]}${s.last[0]}</i><span><b>${s.first} ${s.last}</b><small>Ученик</small></span></div></td><td>${s.gender==="female"?"Жена":"Мъж"}</td><td>${s.email}</td><td><button class="row-action danger-link" data-remove-student="${s.id}">Премахни</button></td></tr>`).join("");document.querySelector("#emptyRoster").hidden=filtered.length>0;document.querySelector("#rosterCount").textContent=roster.length;document.querySelector("#boysCount").textContent=roster.filter(s=>s.gender==="male").length;document.querySelector("#girlsCount").textContent=roster.filter(s=>s.gender==="female").length;document.querySelector("#freePlaces").textContent=Math.max(0,30-roster.length)}
 function renderPicker(){const q=pickerSearch.value.toLowerCase();const available=allStudents.filter(s=>!roster.some(r=>r.id===s.id)&&(s.first+" "+s.last+" "+s.email).toLowerCase().includes(q));pickerList.innerHTML=available.length?available.map(s=>`<button data-pick-student="${s.id}"><span class="person"><i>${s.first[0]}${s.last[0]}</i><span><b>${s.first} ${s.last}</b><small>${s.email}</small></span></span><strong>Добави</strong></button>`).join(""):`<div class="empty-state"><b>Няма свободни ученици</b><span>Всички намерени ученици вече са в класа.</span></div>`}
 function openPicker(){modal.hidden=false;document.body.classList.add("modal-open");renderPicker()}function closePicker(){modal.hidden=true;document.body.classList.remove("modal-open");pickerSearch.value=""}
 document.querySelector("#addStudentToClass").onclick=openPicker;document.querySelector("#closeStudentPicker").onclick=closePicker;document.querySelector("#cancelStudentPicker").onclick=closePicker;modal.addEventListener("click",e=>{if(e.target===modal)closePicker()});pickerSearch.addEventListener("input",renderPicker);[search,gender].forEach(el=>el.addEventListener("input",renderRoster));globalSearch.addEventListener("input",()=>{search.value=globalSearch.value;renderRoster()});pickerList.addEventListener("click",e=>{const button=e.target.closest("[data-pick-student]");if(!button)return;const student=allStudents.find(s=>s.id===Number(button.dataset.pickStudent));if(student){roster.push(student);saveRoster();renderRoster();renderPicker()}});rosterBody.addEventListener("click",e=>{const id=e.target.dataset.removeStudent;if(id&&confirm("Да премахнем ли ученика от този клас?")){roster=roster.filter(s=>s.id!==Number(id));saveRoster();renderRoster()}});renderRoster();
}

document.querySelectorAll(".app nav a").forEach(link=>{if(link.textContent.includes("Класове"))link.href="admin-classes.html"});
const classesGrid=document.querySelector("#classesGrid");
if(classesGrid){
 const seedClasses=[{id:1,grade:"8",letter:"а",teacher:"Мария Иванова",students:24,room:"204",profile:"Чужди езици",status:"active"},{id:2,grade:"9",letter:"б",teacher:"Георги Петров",students:26,room:"112",profile:"Информационни технологии",status:"active"},{id:3,grade:"10",letter:"а",teacher:"Анна Петрова",students:23,room:"207",profile:"Чужди езици",status:"active"},{id:4,grade:"11",letter:"а",teacher:"Елена Димитрова",students:24,room:"305",profile:"Английски и немски език",status:"active"},{id:5,grade:"12",letter:"б",teacher:"Николай Стоянов",students:21,room:"301",profile:"Софтуерни науки",status:"active"}];
 let classes=JSON.parse(localStorage.getItem("energySchoolClasses")||"null")||seedClasses;
 const modal=document.querySelector("#classModal"),form=document.querySelector("#classForm"),search=document.querySelector("#classSearch"),globalSearch=document.querySelector("#classGlobalSearch"),gradeFilter=document.querySelector("#gradeFilter"),statusFilter=document.querySelector("#classStatusFilter");
 function saveClasses(){localStorage.setItem("energySchoolClasses",JSON.stringify(classes))}
 function renderClasses(){const q=search.value.toLowerCase();const filtered=classes.filter(c=>(c.grade+c.letter+c.teacher+c.profile+c.room).toLowerCase().includes(q)&&(gradeFilter.value==="all"||c.grade===gradeFilter.value)&&(statusFilter.value==="all"||c.status===statusFilter.value));classesGrid.innerHTML=filtered.map(c=>`<article class="class-card"><div class="class-top"><span class="class-name">${c.grade}${c.letter}</span><span class="status ${c.status}">${c.status==="active"?"Активен":"Архивиран"}</span></div><h3>${c.profile||"Общообразователна подготовка"}</h3><dl><div><dt>Класен ръководител</dt><dd>${c.teacher}</dd></div><div><dt>Ученици</dt><dd>${c.students}</dd></div><div><dt>Класна стая</dt><dd>${c.room}</dd></div></dl><div class="class-actions"><button data-view="${c.id}">Ученици</button><button data-edit-class="${c.id}">Редактирай</button><button data-archive="${c.id}">${c.status==="active"?"Архивирай":"Активирай"}</button></div></article>`).join("");document.querySelector("#emptyClasses").hidden=filtered.length>0;const active=classes.filter(c=>c.status==="active");document.querySelector("#classesCount").textContent=active.length;document.querySelector("#classStudentsCount").textContent=active.reduce((n,c)=>n+Number(c.students),0);document.querySelector("#classTeachersCount").textContent=new Set(active.map(c=>c.teacher)).size;document.querySelector("#avgStudentsCount").textContent=active.length?Math.round(active.reduce((n,c)=>n+Number(c.students),0)/active.length):0}
 function openClass(c){modal.hidden=false;document.body.classList.add("modal-open");document.querySelector("#classModalTitle").textContent=c?"Редактиране на клас":"Създаване на клас";document.querySelector("#editClassId").value=c?.id||"";document.querySelector("#classGrade").value=c?.grade||"8";document.querySelector("#classLetter").value=c?.letter||"а";document.querySelector("#classTeacher").value=c?.teacher||"";document.querySelector("#classStudents").value=c?.students??24;document.querySelector("#classRoom").value=c?.room||"";document.querySelector("#classProfile").value=c?.profile||""}
 function closeClass(){modal.hidden=true;document.body.classList.remove("modal-open");form.reset()}
 document.querySelector("#addClassButton").onclick=()=>openClass();document.querySelector("#closeClassModal").onclick=closeClass;document.querySelector("#cancelClassModal").onclick=closeClass;modal.addEventListener("click",e=>{if(e.target===modal)closeClass()});[search,gradeFilter,statusFilter].forEach(el=>el.addEventListener("input",renderClasses));globalSearch.addEventListener("input",()=>{search.value=globalSearch.value;renderClasses()});classesGrid.addEventListener("click",e=>{const edit=e.target.dataset.editClass,archive=e.target.dataset.archive,view=e.target.dataset.view;if(edit)openClass(classes.find(c=>c.id===Number(edit)));if(archive){classes=classes.map(c=>c.id===Number(archive)?{...c,status:c.status==="active"?"archived":"active"}:c);saveClasses();renderClasses()}if(view)alert("Списъкът с ученици на този клас ще бъде следващият модул.")});
 form.addEventListener("submit",e=>{e.preventDefault();const id=Number(document.querySelector("#editClassId").value);const record={id:id||Date.now(),grade:document.querySelector("#classGrade").value,letter:document.querySelector("#classLetter").value,teacher:document.querySelector("#classTeacher").value.trim(),students:Number(document.querySelector("#classStudents").value),room:document.querySelector("#classRoom").value.trim(),profile:document.querySelector("#classProfile").value.trim(),status:"active"};if(id)classes=classes.map(c=>c.id===id?{...c,...record}:c);else classes.unshift(record);saveClasses();closeClass();renderClasses()});renderClasses();
}
