const MESSAGE_API="https://energy-school-api.energypublishing.workers.dev";
const messageToken=sessionStorage.getItem("energySchoolToken")||localStorage.getItem("energySchoolToken");
let messageData={user:null,recipients:[],conversations:[]},activeConversationId="";
const list=document.querySelector("#conversations"),chatHeader=document.querySelector("#chatHeader"),chatMessages=document.querySelector("#chatMessages"),search=document.querySelector("#conversationSearch"),messageState=document.querySelector("#messageState");
const escapeHtml=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const roleLabel={student:"Ученик",teacher:"Учител",school_admin:"Директор",parent:"Родител"};
async function messageApi(path,options={}){const r=await fetch(MESSAGE_API+path,{...options,headers:{Authorization:"Bearer "+messageToken,"Content-Type":"application/json"}}),d=await r.json();if(!r.ok)throw new Error(d.error||"Грешка при заявката.");return d}
function buildMessageNav(){const role=messageData.user.role,menus={student:[["⌂","Начало","student.html"],["▣","Оценки","student-diary.html"],["⌁","Домашни","student-homework.html"],["✓","Отсъствия","student-diary.html?tab=attendance"],["□","Програма","student-schedule.html"]],teacher:[["⌂","Начало","teacher.html"],["▣","Електронен дневник","teacher-journal.html"],["★","Срочни оценки","teacher-final-grades.html"],["⌁","Домашни","teacher-homework.html"],["✓","Отсъствия","teacher-attendance.html"],["□","Програма","teacher-schedule.html"]],school_admin:[["⌂","Табло","admin.html"],["♙","Потребители","admin-users.html"],["♚","Родители","admin-parents.html"],["♧","Назначения","admin-assignments.html"],["◆","Предмети","admin-subjects.html"],["▣","Класове","admin-classes.html"],["□","Учебна година","admin-year.html"],["▤","Програма","admin-schedule.html"],["✓","Отсъствия","admin-attendance.html"]],parent:[["⌂","Начало","parent.html"],["⌁","Домашни","parent-homework.html"]]};document.querySelector("#messagesNav").innerHTML=menus[role].map(x=>`<a href="${x[2]}">${x[0]} ${x[1]}</a>`).join("")+'<a href="change-password.html">⚿ Профил и парола</a><a class="active" href="messages.html">✉ Съобщения</a>';document.querySelector("#backToPanel").href=role==="school_admin"?"admin.html":role==="teacher"?"teacher.html":role==="parent"?"parent.html":"student.html"}
async function loadMessageBootstrap(keepActive=true){try{const old=activeConversationId;messageData=await messageApi("/api/messages/bootstrap");buildMessageNav();document.querySelector("#messageRecipient").innerHTML=messageData.recipients.map(r=>`<option value="${escapeHtml(r.id)}">${escapeHtml(r.first_name+" "+r.last_name)} · ${roleLabel[r.role]||""}${r.class_name?" · "+escapeHtml(r.class_name):""}</option>`).join("");activeConversationId=keepActive&&messageData.conversations.some(c=>String(c.id)===String(old))?old:String(messageData.conversations[0]?.id||"");renderConversationList();if(activeConversationId)await openConversation(activeConversationId,false);else renderEmptyChat()}catch(e){messageState.textContent=e.message}}
function initials(name){return name.split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase()}
function renderConversationList(){const q=search.value.toLowerCase();list.innerHTML=messageData.conversations.filter(c=>(c.other_name||c.title||"").toLowerCase().includes(q)).map(c=>{const name=c.other_name||c.title||"Разговор";return `<button class="conversation ${String(c.id)===String(activeConversationId)?"active":""}" data-chat="${c.id}"><i>${initials(name)}</i><span><b>${escapeHtml(name)}</b><small>${escapeHtml(c.last_message||"Нов разговор")}</small></span>${Number(c.unread_count)?`<em>${c.unread_count}</em>`:""}</button>`}).join("")||'<div class="empty-state"><small>Няма разговори</small></div>'}
function renderEmptyChat(){chatHeader.innerHTML="<b>Изберете разговор</b>";chatMessages.innerHTML='<div class="empty-state"><b>Все още няма съобщения</b><p>Натиснете „Ново съобщение“, за да започнете разговор.</p></div>';document.querySelector("#replyForm").hidden=true}
function conversationPath(id){return String(id).startsWith("p-")?"/api/parent-conversations/"+String(id).slice(2)+"/messages":"/api/conversations/"+id+"/messages"}
async function openConversation(id,refreshList=true){activeConversationId=String(id);try{const d=await messageApi(conversationPath(id)),other=d.members.find(m=>String(m.id)!==String(d.currentUserId)),name=other?other.first_name+" "+other.last_name:"Разговор";chatHeader.innerHTML=`<i>${initials(name)}</i><span><b>${escapeHtml(name)}</b><small>${other?roleLabel[other.role]||"":""}${d.contextStudent?" · за "+escapeHtml(d.contextStudent):""}</small></span>`;chatMessages.innerHTML=d.messages.map(m=>`<div class="message ${String(m.sender_id)===String(d.currentUserId)?"me":"them"}"><p>${escapeHtml(m.body).replaceAll("\n","<br>")}</p><small>${new Date(String(m.created_at).replace(" ","T")+"Z").toLocaleString("bg-BG",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"})}</small></div>`).join("");chatMessages.scrollTop=chatMessages.scrollHeight;document.querySelector("#replyForm").hidden=false;if(refreshList){const c=messageData.conversations.find(x=>String(x.id)===String(id));if(c)c.unread_count=0;renderConversationList()}}catch(e){messageState.textContent=e.message}}
list.onclick=e=>{const b=e.target.closest("[data-chat]");if(b)openConversation(b.dataset.chat)};search.oninput=renderConversationList;document.querySelector("#messageGlobalSearch").oninput=e=>{search.value=e.target.value;renderConversationList()};
document.querySelector("#replyForm").onsubmit=async e=>{e.preventDefault();const input=document.querySelector("#replyText"),body=input.value.trim();if(!body||!activeConversationId)return;const button=e.submitter;button.disabled=true;try{await messageApi(conversationPath(activeConversationId),{method:"POST",body:JSON.stringify({body})});input.value="";await openConversation(activeConversationId);await loadMessageBootstrap(true)}catch(x){messageState.textContent=x.message}finally{button.disabled=false}};
const modal=document.querySelector("#newMessageModal");document.querySelector("#newMessageButton").onclick=()=>{document.querySelector("#newMessageError").textContent="";modal.hidden=false};document.querySelectorAll(".new-message-dismiss").forEach(b=>b.onclick=()=>modal.hidden=true);document.querySelector("#newMessageForm").onsubmit=async e=>{e.preventDefault();const button=e.submitter,error=document.querySelector("#newMessageError");button.disabled=true;try{const d=await messageApi("/api/conversations",{method:"POST",body:JSON.stringify({recipientId:document.querySelector("#messageRecipient").value,body:document.querySelector("#newMessageText").value})});e.target.reset();modal.hidden=true;activeConversationId=String(d.conversationId);await loadMessageBootstrap(true)}catch(x){error.textContent=x.message}finally{button.disabled=false}};
loadMessageBootstrap(false);setInterval(()=>loadMessageBootstrap(true),15000);
